version: "2"

networks:
  default.svc.cluster.local:

services:
  ca-root:
    container_name: ca-root
    image: hyperledger/fabric-ca:1.4.3
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - ROOT_HOST=ca-root
      - ROOT_PORT=7054
      - ROOT_USERNAME=admin
      - ROOT_PASSWORD=adminpw
    volumes:
      - ./state/ca-root:/etc/hyperledger/fabric-ca-server
      - ./scripts:/scripts
    command: sh /scripts/start-root.sh
    ports:
      - 7054:7054
    networks: 
      - default.svc.cluster.local
  ca-client:
    container_name: ca-client
    image: hyperledger/fabric-ca-tools:1.2.1
    working_dir: /etc/hyperledger/fabric-ca-client
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-client
      - ROOT_HOST=ca-root
      - ROOT_PORT=7054
      - ROOT_USERNAME=admin
      - ROOT_PASSWORD=adminpw
    volumes:
      - ./state/ca-root:/etc/hyperledger/fabric-ca-server-root
      - ./state/ca-client:/etc/hyperledger/fabric-ca-client
      - ./scripts:/etc/hyperledger/fabric-ca-client/scripts
    command: sleep infinity
    networks: 
      - default.svc.cluster.local
    depends_on:
      - ca-root
