apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-org1-deployment
  labels: {
    component: peer1,
    type: peer,
    org: org1
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer1
      type: peer
      org: org1
  template:
    metadata:
      labels:
        component: peer1
        type: peer
        org: org1
    spec:
      volumes:
        - name: host-mount
          hostPath:
            path: "/host"
        - name: host
          hostPath:
            path: /var/run
      containers:
        - name: peer1-org1
          image: hyperledger/fabric-peer:1.4.3
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["sh"]
          args: ["/scripts/start-peer.sh"]
          env:
            - name: CORE_VM_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_VM_DOCKER_ATTACHOUT
              value: "true"
            - name: CORE_PEER_ID
              value: peer1-org1-service
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org1-service:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer1-org1-service:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer1-org1-service:7051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_PEER_LOCALMSPID
              value: org1
            - name: CORE_PEER_ENDORSER_ENABLED
              value: "true"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: peer1-org1-couchdb:5984
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: CouchDB
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              value: nick
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: /var/run
              name: host
            - mountPath: /etc/hyperledger/fabric/msp
              name: host-mount
              subPath: files/scripts/crypto-config/peerOrganizations/org1/peers/org1-peer1.default.svc.cluster.local/msp
            - mountPath: /etc/hyperledger/fabric/tls
              name: host-mount
              subPath: files/scripts/crypto-config/peerOrganizations/org1/peers/org1-peer1.default.svc.cluster.local/tls
            - mountPath: /var/hyperledger/production
              name: host-mount
              subPath: state/org1/peers/peer1
            - mountPath: /scripts
              name: host-mount
              subPath: files/scripts
