apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-peer1-org1-deployment
  labels: {
    component: peer1,
    type: cli,
    org: org1
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer1
      type: cli
      org: org1
  template:
    metadata:
      labels:
        component: peer1
        type: cli
        org: org1
    spec:
      volumes:
        - name: host-mount
          hostPath:
            path: "/host"
      containers:
        - name: peer1-org1
          image: hyperledger/fabric-tools:1.4.3
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: cli-peer1-org1
            - name: CORE_PEER_ADDRESS
              value: peer1-org1-service:7051
            - name: CORE_PEER_LOCALMSPID
              value: org1
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/fabric/msp/users/Admin@org1/msp
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
              name: host-mount
              subPath: files/scripts/orderer
            - mountPath: /opt/gopath/src/rawresources
              name: host-mount
              subPath: files/scripts/chaincode/rawresources
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channels
              name: host-mount
              subPath: files/scripts/channels
            - mountPath: /etc/hyperledger/fabric/msp
              name: host-mount
              subPath: files/scripts/crypto-config/peerOrganizations/org1
            - mountPath: /etc/hyperledger/fabric/tls
              name: host-mount
              subPath: files/scripts/crypto-config/peerOrganizations/org1/peers/org1-peer1.default.svc.cluster.local/tls
            - mountPath: /etc/hyperledger/orderers
              name: host-mount
              subPath: files/scripts/crypto-config/ordererOrganizations/default.svc.cluster.local
