apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org2-couchdb-deployment
  labels: {
    component: peer0,
    type: couchdb,
    org: org2
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer0
      type: couchdb
      org: org2
  template:
    metadata:
      labels:
        component: peer0
        type: couchdb
        org: org2
    spec:
      volumes:
        - name: host-mount
          persistentVolumeClaim:
            claimName: efs-burst-persistent-volume-claim
      containers:
        - name: peer0-org2-couchdb
          image: couchdb:2.3.1
          env:
            - name: COUCHDB_USER
              value: nick
            - name: COUCHDB_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: host-mount
              subPath: state/org2/peers/peer0-couchdb
