version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  hyperledger:

services:
  # Orderers
  orderer0:
    container_name: orderer0
    image: hyperledger/fabric-orderer:2.2
    working_dir: /var/hyperledger/orderer
    restart: always
    environment: 
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISPROFILE=OrdererGenesis
      - ORDERER_GENERAL_SYSTEMCHANNEL=system-channel
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/data/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACOTR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./crypto-config/ordererOrganizations/orderer/orderers/orderer0/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/orderer/orderers/orderer0/tls:/var/hyperledger/orderer/tls
      - ./state/orderer0:/var/hyperledger/production/orderer
      - ./orderer:/var/hyperledger/orderer/data
    ports:
      - 7050:7050
    networks:
      - hyperledger
  orderer1:
    container_name: orderer1
    image: hyperledger/fabric-orderer:2.2
    working_dir: /var/hyperledger/orderer
    restart: always
    environment: 
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISPROFILE=OrdererGenesis
      - ORDERER_GENERAL_SYSTEMCHANNEL=system-channel
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/data/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACOTR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./crypto-config/ordererOrganizations/orderer/orderers/orderer1/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/orderer/orderers/orderer1/tls:/var/hyperledger/orderer/tls
      - ./state/orderer1:/var/hyperledger/production/orderer
      - ./orderer:/var/hyperledger/orderer/data
    ports:
      - 8050:7050
    networks:
      - hyperledger
  orderer2:
    container_name: orderer2
    image: hyperledger/fabric-orderer:2.2
    environment: 
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISPROFILE=OrdererGenesis
      - ORDERER_GENERAL_SYSTEMCHANNEL=system-channel
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/data/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACOTR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./crypto-config/ordererOrganizations/orderer/orderers/orderer2/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/orderer/orderers/orderer2/tls:/var/hyperledger/orderer/tls
      - ./state/orderer2:/var/hyperledger/production/orderer
      - ./orderer:/var/hyperledger/orderer/data
    ports:
      - 9050:7050
    networks:
      - hyperledger

  # Org1 Peers
  peer0-org1-couchdb:
    image: couchdb:2.3.1
    container_name: peer0-org1-couchdb
    restart: always
    environment:
      - COUCHDB_USER=nick
      - COUCHDB_PASSWORD=1234
    volumes:
      - ./state/peer0-org1-couchdb:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      - hyperledger
  peer0-org1:
    image: hyperledger/fabric-peer:2.2
    container_name: peer0-org1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    restart: always
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer0-org1
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org1:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-org1:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-org1:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=org1
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-org1-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=nick
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/org1/peers/peer0-org1/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1/peers/peer0-org1/tls:/etc/hyperledger/fabric/tls
      - ./state/peer0-org1:/var/hyperledger/production
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ./scripts/:/scripts/
    ports:
      - 7051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger
  peer1-org1-couchdb:
    image: couchdb:2.3.1
    container_name: peer1-org1-couchdb
    restart: always
    environment:
      - COUCHDB_USER=nick
      - COUCHDB_PASSWORD=1234
    volumes:
      - ./state/peer1-org1-couchdb:/opt/couchdb/data
    ports:
      - 6984:5984
    networks:
      - hyperledger
  peer1-org1:
    image: hyperledger/fabric-peer:2.2
    container_name: peer1-org1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    restart: always
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer1-org1
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org1:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1-org1:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=org1
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-org1-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=nick
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/org1/peers/peer1-org1/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1/peers/peer1-org1/tls:/etc/hyperledger/fabric/tls
      - ./state/peer1-org1:/var/hyperledger/production
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ./scripts/:/scripts/
    ports:
      - 8051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger

  # Org2 Peers
  peer0-org2-couchdb:
    image: couchdb:2.3.1
    container_name: peer0-org2-couchdb
    restart: always
    environment:
      - COUCHDB_USER=nick
      - COUCHDB_PASSWORD=1234
    volumes:
      - ./state/peer0-org2-couchdb:/opt/couchdb/data
    ports:
      - 7984:5984
    networks:
      - hyperledger
  peer0-org2:
    image: hyperledger/fabric-peer:2.2
    container_name: peer0-org2
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    restart: always
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer0-org2
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org2:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-org2:9051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-org2:9051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=org2
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-org2-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=nick
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/org2/peers/peer0-org2/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2/peers/peer0-org2/tls:/etc/hyperledger/fabric/tls
      - ./state/peer0-org2:/var/hyperledger/production
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ./scripts/:/scripts/
    ports:
      - 9051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger
  peer1-org2-couchdb:
    image: couchdb:2.3.1
    container_name: peer1-org2-couchdb
    restart: always
    environment:
      - COUCHDB_USER=nick
      - COUCHDB_PASSWORD=1234
    volumes:
      - ./state/peer1-org2-couchdb:/opt/couchdb/data
    ports:
      - 8984:5984
    networks:
      - hyperledger
  peer1-org2:
    image: hyperledger/fabric-peer:2.2
    container_name: peer1-org2
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    restart: always
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer1-org2
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-org2:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2:10051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1-org2:10051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=org2
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-org2-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=nick
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ./crypto-config/peerOrganizations/org2/peers/peer1-org2/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2/peers/peer1-org2/tls:/etc/hyperledger/fabric/tls
      - ./state/peer1-org2:/var/hyperledger/production
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ./scripts/:/scripts/
    ports:
      - 10051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger

  # CLIs
  cli-peer0-org1:
    container_name: cli-peer0-org1
    image: hyperledger/fabric-tools:2.2
    restart: always
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true

      - CORE_PEER_ID=cli-peer0-org1
      - CORE_PEER_ADDRESS=peer0-org1:7051
      - CORE_PEER_LOCALMSPID=org1
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/users/Admin@org1/msp

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ./orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ./chaincode/resources:/opt/gopath/src/resources
      - ./chaincode/resource_types:/opt/gopath/src/resource_types
      - ./channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ./crypto-config/peerOrganizations/org1:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1/peers/peer0-org1/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
    depends_on:
      - peer0-org1
    command: sleep 500000
    networks:
      - hyperledger

  cli-peer1-org1:
    container_name: cli-peer1-org1
    image: hyperledger/fabric-tools:2.2
    restart: always
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true

      - CORE_PEER_ID=cli-peer1-org1
      - CORE_PEER_ADDRESS=peer1-org1:8051
      - CORE_PEER_LOCALMSPID=org1
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/users/Admin@org1/msp

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ./orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ./chaincode/resources:/opt/gopath/src/resources
      - ./chaincode/resource_types:/opt/gopath/src/resource_types
      - ./channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ./crypto-config/peerOrganizations/org1:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1/peers/peer1-org1/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
    depends_on:
      - peer0-org1
    command: sleep 500000
    networks:
      - hyperledger

  cli-peer0-org2:
    container_name: cli-peer0-org2
    image: hyperledger/fabric-tools:2.2
    restart: always
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true

      - CORE_PEER_ID=cli-peer0-org2
      - CORE_PEER_ADDRESS=peer0-org2:9051
      - CORE_PEER_LOCALMSPID=org2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/users/Admin@org2/msp

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ./orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ./chaincode/resources:/opt/gopath/src/resources
      - ./chaincode/resource_types:/opt/gopath/src/resource_types
      - ./channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ./crypto-config/peerOrganizations/org2:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2/peers/peer0-org2/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
    depends_on:
      - peer0-org2
    command: sleep 500000
    networks:
      - hyperledger

  cli-peer1-org2:
    container_name: cli-peer1-org2
    image: hyperledger/fabric-tools:2.2
    restart: always
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true

      - CORE_PEER_ID=cli-peer1-org2
      - CORE_PEER_ADDRESS=peer1-org2:10051
      - CORE_PEER_LOCALMSPID=org2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/users/Admin@org2/msp

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ./orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ./chaincode/resources:/opt/gopath/src/resources
      - ./chaincode/resource_types:/opt/gopath/src/resource_types
      - ./channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ./crypto-config/peerOrganizations/org2:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2/peers/peer1-org2/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
    depends_on:
      - peer1-org2
    command: sleep 500000
    networks:
      - hyperledger


  explorerdb:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb
    hostname: explorerdb
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on:
      - peer0-org1
      - peer1-org1
      - peer0-org2
      - peer1-org2
    networks:
      - hyperledger

  explorer:
    image: hyperledger/explorer:latest
    container_name: explorer
    hostname: explorer
    environment:
      - DATABASE_HOST=explorerdb
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./explorer/organizations:/tmp/crypto
      - walletstore:/opt/wallet
    command: sh -c "node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8080:8080
    depends_on:
      explorerdb:
        condition: service_healthy
    networks:
      - hyperledger